import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Edit3, LoaderCircle, Plus, Trash2, UserRound, X } from 'lucide-react'
import { useOutletContext } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { createTimetableEntryApi, deleteTimetableEntryApi, getTimetableRangeApi, getTimetableTeachersApi, updateTimetableEntryApi } from '../api/timetable.api'

const todayIndia=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const v=Object.fromEntries(p.map(x=>[x.type,x.value]));return v.year+'-'+v.month+'-'+v.day}
const d=v=>new Date(v+'T00:00:00Z')
const offset=(v,n)=>{const x=d(v);x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
const monday=v=>{const day=d(v).getUTCDay();return offset(v,day===0?-6:1-day)}
const weekDays=v=>Array.from({length:7},(_,i)=>offset(monday(v),i))
const label=v=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short'}).format(d(v))
const full=v=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'long',year:'numeric'}).format(d(v))
const weekday=v=>new Intl.DateTimeFormat('en-IN',{weekday:'short'}).format(d(v))
const month=v=>new Intl.DateTimeFormat('en-IN',{month:'long',year:'numeric'}).format(d(v))
const blank=date=>({date,startTime:'08:00',endTime:'09:00',subject:'',className:'',room:'',teacherId:'',notes:''})

export default function TimetablePage(){
  const {role}=useOutletContext(); const {token}=useAuth(); const principal=role==='principal'; const today=useMemo(todayIndia,[])
  const [selected,setSelected]=useState(today),[entries,setEntries]=useState([]),[teachers,setTeachers]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[editId,setEditId]=useState(null),[form,setForm]=useState(blank(today))
  const days=useMemo(()=>weekDays(selected),[selected]), from=days[0], to=days[6]
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await getTimetableRangeApi(token,from,to);setEntries(r.entries||[])}catch(e){setError(e.message||'Unable to load timetable.')}finally{setLoading(false)}},[token,from,to])
  useEffect(()=>{load()},[load])
  useEffect(()=>{if(!principal)return;getTimetableTeachersApi(token).then(r=>setTeachers(r.teachers||[])).catch(e=>setError(e.message||'Unable to load teachers.'))},[principal,token])
  const grouped=useMemo(()=>{const m=Object.fromEntries(days.map(x=>[x,[]]));entries.forEach(x=>m[x.date]?.push(x));Object.values(m).forEach(x=>x.sort((a,b)=>a.startTime.localeCompare(b.startTime)));return m},[days,entries])
  const create=date=>{setEditId(null);setForm(blank(date));setError('');setOpen(true)}
  const edit=x=>{setEditId(x.id);setForm({date:x.date,startTime:x.startTime,endTime:x.endTime,subject:x.subject,className:x.className,room:x.room||'',teacherId:x.teacher?.id||'',notes:x.notes||''});setError('');setOpen(true)}
  const save=async e=>{e.preventDefault();setSaving(true);setError('');try{if(editId)await updateTimetableEntryApi(token,editId,form);else await createTimetableEntryApi(token,form);setOpen(false);await load()}catch(e){setError(e.message||'Unable to save lecture.')}finally{setSaving(false)}}
  const remove=async x=>{if(!window.confirm('Remove '+x.subject+' from '+full(x.date)+'?'))return;try{await deleteTimetableEntryApi(token,x.id);await load()}catch(e){setError(e.message||'Unable to remove lecture.')}}
  return <><div className="timetable-page">
    <div className="timetable-head"><div><span className="eyebrow">TIMETABLE</span><h2>{principal?'Plan classes and lectures':'Lecture timetable'}</h2><p>{principal?'Set today’s lectures and manage the schedule for any date.':'View the published schedule for any date.'}</p></div>{principal&&<button className="primary" onClick={()=>create(selected)}><Plus size={16}/> Add lecture</button>}</div>
    {error&&<div className="attendance-admin-error">{error}</div>}
    <section className="timetable-toolbar"><button className="icon-button" onClick={()=>setSelected(offset(selected,-7))}><ChevronLeft size={17}/></button><button className="icon-button" onClick={()=>setSelected(offset(selected,7))}><ChevronRight size={17}/></button><div className="timetable-period"><CalendarDays size={17}/><div><span>WEEK</span><strong>{month(from)} · {label(from)} — {label(to)}</strong></div></div><button className="secondary" onClick={()=>setSelected(today)}>Today</button><label className="timetable-date-picker"><span>Jump to date</span><input type="date" value={selected} onChange={e=>setSelected(e.target.value)}/></label></section>
    <section className="timetable-selected-day"><div><span className="eyebrow">{selected===today?'TODAY':'SELECTED DAY'}</span><h3>{full(selected)}</h3></div><span>{grouped[selected]?.length||0} lectures</span></section>
    <section className="timetable-grid-wrap">{loading?<div className="timetable-state"><LoaderCircle size={18} className="spin"/>Loading timetable...</div>:<div className="timetable-grid">{days.map(day=><div key={day} className={'timetable-day '+(day===selected?'selected':'')}><button className="timetable-day-head" onClick={()=>setSelected(day)}><span>{weekday(day)}</span><strong>{label(day)}</strong>{day===today&&<em>Today</em>}</button><div className="timetable-day-body">{grouped[day]?.length?grouped[day].map(x=><article className="timetable-lecture" key={x.id} onClick={()=>principal&&edit(x)}><div className="timetable-lecture-time"><Clock3 size={12}/><strong>{x.startTime}</strong><span>{x.endTime}</span></div><h4>{x.subject}</h4><p>{x.className}{x.room?' · '+x.room:''}</p>{x.teacher&&<span className="timetable-teacher"><UserRound size={11}/>{x.teacher.name}</span>}{principal&&<div className="timetable-lecture-actions"><button type="button" onClick={e=>{e.stopPropagation();edit(x)}}><Edit3 size={12}/></button><button type="button" onClick={e=>{e.stopPropagation();remove(x)}}><Trash2 size={12}/></button></div>}</article>):<div className="timetable-empty">{principal?<button onClick={()=>create(day)}><Plus size={14}/> Add lecture</button>:<span>No lectures</span>}</div>}</div></div>)}</div>}</section>
  </div>
  {open&&<div className="timetable-modal-backdrop" onMouseDown={()=>!saving&&setOpen(false)}><section className="timetable-modal" onMouseDown={e=>e.stopPropagation()}><div className="user-modal-head"><div><span className="eyebrow">{editId?'EDIT LECTURE':'NEW LECTURE'}</span><h3>{editId?'Update lecture':'Add lecture'}</h3><p>Schedule a lecture for any date.</p></div><button className="modal-close" onClick={()=>!saving&&setOpen(false)}><X size={18}/></button></div><form onSubmit={save} className="timetable-form"><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><div className="timetable-form-row"><label>Start time<input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})} required/></label><label>End time<input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})} required/></label></div><div className="timetable-form-row"><label>Subject<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Mathematics" required/></label><label>Class<input value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="12th Science" required/></label></div><div className="timetable-form-row"><label>Teacher<select value={form.teacherId} onChange={e=>setForm({...form,teacherId:e.target.value})}><option value="">Select teacher</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Room<input value={form.room} onChange={e=>setForm({...form,room:e.target.value})} placeholder="Room 04"/></label></div><label>Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optional lecture note"/></label>{error&&<div className="login-error user-modal-error">{error}</div>}<div className="user-modal-actions"><button type="button" className="secondary" onClick={()=>!saving&&setOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving&&<LoaderCircle size={15} className="spin"/>}{saving?'Saving...':editId?'Update lecture':'Add lecture'}</button></div></form></section></div>}</>
}